# Generated by Django 4.2.4 on 2023-09-03 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_mainfeatured_product_productdetail_productimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='deatil',
            new_name='detail',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.CharField(default='1', max_length=125),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductStock',
        ),
    ]
